my_string=input('Тяжело в учении, легко в программировании: ')
print(len(my_string))
print('Тяжело в учении, легко в программировании'.upper())
print('Тяжело в учении, легко в программировании'.lower())
print(my_string.replace(' ',''))
print(my_string[0])
print(my_string[-1])